language: c

dist: xenial

os:
  - linux

addons:
  apt_packages:
    - gfortran

before_install:
  - pip install --user cpp-coveralls

script:
  - bash .travis/compile_benchmark.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'

cache:
  apt: true
  pip: true
