language: c

dist: xenial

os:
  - linux

addons:
  apt_packages:
    - gfortran

script:
  - bash .travis/compile_benchmark.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  apt: true
  pip: true
